---
    backend:
      name: git-gateway
      branch: master
    media_folder: static/img
    public_folder: "/img"
    collections:
    - name: home
      label: Home
      folder: content/home
      create: false
      editor:
        preview: true
      fields:
      - label: Title
        name: title
        widget: string
      - label: Text
        name: text
        widget: markdown
    - name: pages
      label: Pages
      files: 
        - label: "Contact"
          name: "contact"
          file: "content/contact.md"
          fields:
            - {label: Title, name: title, widget: string}
            - {label: Right Column, name: rightColumn, widget: markdown}
            - {label: Left Column, name: leftColumn, widget: markdown}
        - label: "Home"
          name: "home"
          file: "content/_index.md"
          fields:
            - {label: Title, name: title, widget: string}
            - {label: Hero Image, name: heroImage, widget: image}
            - {label: Heading, name: heading, widget: string}
            - label: Sections
              name: sections
              widget: list
              fields:
                - {label: Title, name: title, widget: string}
                - {label: Body, name: body, widget: markdown}
    - name: blog
      label: Blog
      folder: content/blog
      create: true
      slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
      editor:
        preview: false
      fields:
      - label: Title
        name: title
        widget: string
      - label: Publish Date
        name: date
        widget: datetime
      - label: Description
        name: description
        widget: string
      - label: Body
        name: body
        widget: markdown
    - name: case
      label: Case
      folder: content/case
      create: true
      slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
      editor:
        preview: false
      fields:
      - label: Title
        name: title
        widget: string
      - label: Publish Date
        name: date
        widget: datetime
      - label: Description
        name: description
        widget: string
      - label: Body
        name: body
        widget: markdown
    - name: staff
      label: Staff
      folder: content/staff
      create: true
      slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
      editor:
        preview: false
      fields:
      - label: Title
        name: title
        widget: string
      - label: Intro
        name: intro
        widget: markdown
      - label: Team
        name: team
        widget: list
        fields:
        - label: Name
          name: name
          widget: string
        - label: Image
          name: image
          widget: image
        - label: Position
          name: position
          widget: string
        - label: Email
          name: email
          widget: string
        - label: LinkedIn
          name: linkedin
          widget: string
        - label: Phone
          name: phone
          widget: string
        - label: Description
          name: description
          widget: markdown
      - label: Board
        name: board
        widget: list
        fields:
        - label: Name
          name: name
          widget: string
        - label: Image
          name: image
          widget: image
        - label: Position
          name: position
          widget: string
        - label: Email
          name: email
          widget: string
        - label: LinkedIn
          name: linkedin
          widget: string
        - label: Phone
          name: phone
          widget: string
        - label: Description
          name: description
          widget: markdown
    